### ISSUE TITLE
How come the change in #10 to add RestAzured Slack was removed? 

### ISSUE THREAD

**Issue by kilasuit** [CloudFamily/CloudFamily#51]
I'm confused as to why #10 was merged, which included the link to the long established RestAzured Slack community and then in the very next commit to the `_index.en.md` file this was then removed from the file, without a comment.

https://github.com/CloudFamily/CloudFamily/commit/4cb92e55a39c999ef56753b0f8f77ccba15c76e9#diff-c5f617d55dbf42f5bb92760d3b0e41c2 

I would find it useful to understand why this happened? and why a comment about why it was removed was not added, either publicly or privately

**Comment by PixelRobots** [comment]
Hi Ryan, I believe, but could be mistaken that it was moved to this page https://cloudfamily.info/useful_links/ as there are more slack links than just the cloud family and restazured.

Thanks

Richard

**Comment by kilasuit** [comment]
Fair enough I had not seen it that it had been added there & would have looked there if the commit message had been clearer in what had been changed.
